# Generated by Django 5.0.2 on 2024-02-14 01:09

import django.db.models.deletion
import phonenumber_field.modelfields
import tracker.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('origin_address1', models.CharField(max_length=80)),
                ('origin_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('origin_city', models.CharField(max_length=80)),
                ('origin_state_province', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AB', 'Alberta'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('BC', 'British Columbia'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MB', 'Manitoba'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NB', 'New Brunswick'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NL', 'Newfoundland and Labrador'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('ON', 'Ontario'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('RI', 'Rhode Island'), ('SK', 'Saskatchewan'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('YT', 'Yukon Territory'), ('DC', 'District of Columbia'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands')], max_length=2)),
                ('origin_postal_code', models.CharField(max_length=7, validators=[tracker.utils.validate_postal_code])),
                ('origin_country', models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40)),
                ('destination_address1', models.CharField(max_length=80)),
                ('destination_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('destination_city', models.CharField(max_length=80)),
                ('destination_state_province', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AB', 'Alberta'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('BC', 'British Columbia'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MB', 'Manitoba'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NB', 'New Brunswick'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NL', 'Newfoundland and Labrador'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('ON', 'Ontario'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('RI', 'Rhode Island'), ('SK', 'Saskatchewan'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('YT', 'Yukon Territory'), ('DC', 'District of Columbia'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands')], max_length=2)),
                ('destination_postal_code', models.CharField(max_length=7, validators=[tracker.utils.validate_postal_code])),
                ('destination_country', models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('primary_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secondary_users', models.ManyToManyField(related_name='moves_as_secondary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Appliance', 'Appliance'), ('Bag', 'Bag'), ('Box', 'Box'), ('Crate', 'Crate'), ('Furniture', 'Furniture'), ('Other', 'Other'), ('Storage Bin', 'Storage Bin'), ('Suitcase', 'Suitcase')], default='Box', max_length=40)),
                ('room', models.CharField(blank=True, help_text='In which room does this parcel belong when it reaches the destination?', max_length=40, null=True)),
                ('contents', models.TextField(help_text='Optionally, describe the contents of this parcel.')),
                ('photo', models.ImageField(max_length=255, upload_to='images/')),
                ('weight', models.FloatField(blank=True, help_text='Optionally, enter the weight of the parcel in pounds.', null=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('In Transit', 'In Transit'), ('Lost', 'Lost'), ('Received', 'Received'), ('Damaged', 'Damaged'), ('Accepted', 'Accepted')], default='Ready', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.move')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=40)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=40)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
