# Generated by Django 5.0.2 on 2024-02-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='contents',
            field=models.TextField(blank=True, help_text='Optionally, describe the contents of this parcel.', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
