# Generated by Django 5.0.2 on 2024-02-24 03:55

import tracker.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_parcel_contents_alter_parcel_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='destination_address1',
            field=models.CharField(max_length=80, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='move',
            name='destination_address2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='move',
            name='destination_city',
            field=models.CharField(max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='move',
            name='destination_country',
            field=models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='move',
            name='destination_postal_code',
            field=models.CharField(max_length=7, validators=[tracker.utils.validate_postal_code], verbose_name='Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='move',
            name='destination_state_province',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AB', 'Alberta'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('BC', 'British Columbia'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MB', 'Manitoba'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NB', 'New Brunswick'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NL', 'Newfoundland and Labrador'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('ON', 'Ontario'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('RI', 'Rhode Island'), ('SK', 'Saskatchewan'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('YT', 'Yukon Territory'), ('DC', 'District of Columbia'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands')], max_length=2, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_address1',
            field=models.CharField(max_length=80, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_address2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_city',
            field=models.CharField(max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_country',
            field=models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_postal_code',
            field=models.CharField(max_length=7, validators=[tracker.utils.validate_postal_code], verbose_name='Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin_state_province',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AB', 'Alberta'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('BC', 'British Columbia'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MB', 'Manitoba'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NB', 'New Brunswick'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NL', 'Newfoundland and Labrador'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('ON', 'Ontario'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('RI', 'Rhode Island'), ('SK', 'Saskatchewan'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('YT', 'Yukon Territory'), ('DC', 'District of Columbia'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands')], max_length=2, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='move',
            name='secondary_users',
            field=models.ManyToManyField(related_name='moves_as_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Add Users'),
        ),
    ]
