# Generated by Django 5.0.2 on 2024-03-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('In Transit', 'In Transit'), ('Lost', 'Lost'), ('Received', 'Received'), ('Damaged', 'Damaged'), ('Accepted', 'Accepted')], default='Ready', max_length=12),
        ),
    ]
